### ISSUE TITLE
I want to add a button to switch between light and dark mode.

### ISSUE THREAD

**Issue by RhyshaKachari** [jimmy-byte/-HactoberFest2022-For_All_Beginers-#171]
I want to add a button to switch between light and dark mode. It can be done easily using javascript and CSS.  I want to contribute to this issue. Kindly assign it to me :)

**Comment by rakshitmehra** [comment]
I want to contribute to ur Project. I can add button to switch between light and dark mode. Kindly assign this project to me........

**Comment by thakurdiwakar** [comment]
Hey,Please assigned me ,i want to contribute .

**Comment by harshraj78** [comment]
Hey RhyshaKachari Please assigned me ,i want to contribute  on this.

**Comment by ErSuyog16** [comment]
Hey  RhyshaKachari this is suyog from  NIT Surat , I wanna contribute to your project..I'm good full stack developer..I can add button that can switch between light and black please assign it to me so that I can contribute..
