### ISSUE TITLE
Change year from 2020 to 2022

### ISSUE THREAD

**Issue by E-fais** [jimmy-byte/-HactoberFest2022-For_All_Beginers-#293]
![E831ADA6-2B70-419A-9156-5EE01DB51FE8](https://user-images.githubusercontent.com/102040088/194757767-0cf1684b-d464-4565-8c6d-8de9c3d428d4.jpeg)

**Comment by ShubhamKumar1095** [comment]
assign this issue to me

**Comment by Purvesh77** [comment]
Hey @E-fais I have already solved this issue.
Can you merge my PR ?
Thank You !

**Comment by AdityaPranav05** [comment]
hi sir, can you assign this to me.

**Comment by teenakc** [comment]
HI , Please assign this to me.

**Comment by E-fais** [comment]
I am not maintainer for this project ;)
